[ticrypt.backup.mongodb.database]
type = "string"
description = "The name of the database in which data will be stored"
default = "ticrypt-backup"
required = true

[ticrypt.backup.mongodb.hostname]
type = "hostname"
description = "Hostname of the backup database. You may EITHER specify the uri OR the components. If specified, the URI will be used instead of the components"
default = "localhost"
required = false

[ticrypt.backup.mongodb.port]
type = "port"
description = "Port of the backup database. You may EITHER specify the uri OR the components. If specified, the URI will be used instead of the components"
default = 27017
required = false

[ticrypt.backup.identifier]
type = "string"
description = "Prefix of backup directory name"
default = "ticrypt"
required = true

[ticrypt.backup.backup-base]
type = "dir"
description = "Directory where backups are stored locally"
default = "/storage/ticrypt/ticrypt-backup"
required = true

[ticrypt.backup.storage-base]
type = "dir"
description = "Directory where the files are located. Must be the same as ticrypt-storage"
default = "/storage/ticrypt/ticrypt-storage"
required = true

[ticrypt.backup.num-copy-actors]
type = "int"
description = "The amout of parallelism for file copying. For aggressive file systems, a larger nubmer might give better performance"
default = 1
required = true

[ticrypt.backup.sqlite.wal]
type = "switch"
description = "[on/off] Whether or not SQLite3 write-ahead-log is used"
default = "off"
required = true

[ticrypt.backup.public-key-location]
type = "file"
description = "Location of the tiCrypt public key. This is used to transfer SFTP backups"
default = "/var/lib/ticrypt/.ssh/id_rsa.pub"
required = true

[ticrypt.backup.akka.actor.provider]
type = "string"
description = "Akka configuration - specify the provider for Backup service messages"
default = "remote"
required = false

[ticrypt.backup.akka.actor.remote.artery.transport]
type = "string"
description = "Set the transport method used for the remote service"
default = "tcp"
required = false

[ticrypt.backup.akka.remote.artery.canonical.hostname]
type = "regex<ipv4>"
description = "Sets the host interface upon which the service listens for connections from the other services."
default = 127.0.0.1
required = false

[ticrypt.backup.akka.remote.artery.canonical.port]
type = "port"
description = "Sets the port used for remote connections to other services."
default = 2564
required = false

[ticrypt.backup.akka.actor.loggers]
type = "[]string"
description = "Set the services to which log files from akka will be sent"
default = ["akka.event.slf4j.Slf4jLogger"]
required = false

[ticrypt.backup.akka.actor.loglevel]
type = "string"
description = "Set the logging level used by the remote service"
default = "INFO"
required = false

[ticrypt.auth.hostname]
type = "hostname"
description = "Sets the hostname used by the Authentication service. Must be set properly for proper communcation with the authentication service."
default = 127.0.0.1
required = false

[ticrypt.auth.port]
type = "port"
description = "Sets the port used by the Authentication service. Must be set properly for proper communcation with the authentication service."
default = 2552
required = false