[ticrypt.proxy.interface]
type = "string"
description = "Interface upon which to listen for proxied connections"
default = "localhost"
required = true

[ticrypt.proxy.ports]
type = "[]string"
description = """
Ports upon which to listen for proxied connections.
Should be specified as an array of ports or inclusive port ranges.
For example: ports = [ 6010-6015, 6025 ] would listen on ports 6010, 6011, 6012, 6013, 6014, 6015, and 6025
"""
default = []
required = true

[ticrypt.proxy.proxy-ttl]
type = "duration"
description = "The amount of time the client has to start a connection after a binding has been created"
default = "5 minutes"
required = true

[ticrypt.proxy.akka.remote.artery.canonical]
hostname = { type = "string", description = "Sets the host interface upon which the service listens for connections from the other services.", default = "127.0.0.1", required = false}
port = { type = "number", description = "Sets the port used for remote connections to other services.", default = "2557", required = false}


[ticrypt.auth]
hostname = { type = "string", description = "Sets the hostname used by the Authentication service. Must be set properly for proper communcation with the authentication service.", default = "127.0.0.1", required = false}
port = { type = "number", description = "Sets the port used by the Authentication service. Must be set properly for proper communcation with the authentication service.", default = "2552", required = false}