[ticrypt.logger.drivers.main-file-logger.main]
type = "boolean"
description = "Whether or not this logger is the main(default) one"
default = true
required = false

[ticrypt.logger.drivers.main-file-logger.immutable]
type = "string"
description = "Whether or not this logger is immutable."
default = true
required = false

[ticrypt.logger.drivers.main-file-logger.type]
type = "string"
description = "[file / tcp / ...] This string tells the logging service which type of driver to use for this driver. Example types are 'file' and 'tcp'."
default = "file"
required = false

[ticrypt.logger.drivers.main-file-logger.log-file]
type = "string"
description = "Where to read and write the logs to"
default = "/var/log/ticrypt/ticrypt-secure-log.log"
required = false

[ticrypt.logger.rotate-log]
type = "string"
description = "[on/off] Whether or not to rotate the main log"
default = "on"
required = false

[ticrypt.logger.rotate-log-frequency]
type = "duration"
description = "The frequency at which to rotate"
default = "1 day"
required = false

[ticrypt.logger.rotate-log-suffix-format]
type = "string"
description = """
Format for the suffix appended to rotated log files. Based on the time at which the log was rotated. Should be a joda datetime format string
See: http://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html"""
default = "'-'yyyyMMdd'T'HHmmss"
required = false

[ticrypt.logger.rotate-log-suffix-timezone]
type = "string"
description = "Set to null to use the default system timezone. If you do this, it is recommended to add a timezone component to the suffix format"
default = "UTC"
required = false

[ticrypt.logger.max-buffered-lines]
type = "number"
description = "Maximum number of lines to buffer before writing out to file"
default = 10
required = false

[ticrypt.logger.akka.remote.artery.canonical]
hostname = { type = "string", description = "Sets the host interface upon which the service listens for connections from the other services.", default = "127.0.0.1", required = false}
port = { type = "number", description = "Sets the port used for remote connections to other services.", default = "2559", required = false}

[ticrypt.auth]
hostname = { type = "string", description = "Sets the hostname used by the Authentication service. Must be set properly for proper communcation with the authentication service.", default = "127.0.0.1", required = false}
port = { type = "number", description = "Sets the port used by the Authentication service. Must be set properly for proper communcation with the authentication service.", default = "2552", required = false}
